import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import type { RetailerSource, FetchResult, RawOffer } from './types';

/**
 * One Dutch sports retailer, backed by a seed file in data/seed/.
 *
 * These files are generated by mock/generate-fakedata.mjs from the SAME
 * catalogue as lib/fakeData.ts — so the identical 49 products and 123 offers
 * reach the front end whether they come from a TypeScript file or from
 * Postgres. That equivalence is the point of the trial run: if the site looks
 * the same both ways, the seam works.
 *
 * ⚠️  THE SLUG MUST BE THE STORE NAME THE CONTRACT USES — "bol.com", not
 *     "bol-com". The front end joins DELIVERY_RULES to offers on this exact
 *     string, so a slug that merely looks tidy silently breaks the smart-split
 *     maths: every delivery fee resolves to zero and the planner confidently
 *     recommends the wrong basket. The equivalence check caught this; nothing
 *     else would have, because no endpoint errors.
 *
 * ⚠️  Invented prices. This is the shape a real Odyssey or Awin feed will drop
 *     into — when one arrives, it is this class with a CSV/XML parser in place
 *     of JSON.parse, and `sourceKind: 'affiliate_feed'`.
 */
export class DutchSeedSource implements RetailerSource {
  readonly sourceKind = 'fixture' as const;

  constructor(
    /** Must match the contract's `Offer.store` exactly. */
    readonly slug: string,
    readonly name: string,
    readonly homepageUrl: string,
    readonly deliveryFeeCents: number,
    readonly freeAboveCents: number,
    /** Filename-safe form, e.g. "bol-com.json". */
    private readonly file: string
  ) {}

  async fetch(): Promise<FetchResult> {
    const path = fileURLToPath(new URL(`../../data/seed/${this.file}`, import.meta.url));
    const rawPayload = await readFile(path, 'utf8');
    const parsed = JSON.parse(rawPayload) as { products: RawOffer[] };
    if (!Array.isArray(parsed.products)) {
      throw new Error(`${this.slug}: seed file has no products array`);
    }
    return { offers: parsed.products, rawPayload };
  }
}

/** The five Dutch sports retailers, with the delivery rules the planner uses. */
export const DUTCH_SEEDS = [
  new DutchSeedSource('decathlon.nl',  'Decathlon',  'https://www.decathlon.nl',  399, 3000, 'decathlon-nl.json'),
  new DutchSeedSource('jdsports.nl',   'JD Sports',  'https://www.jdsports.nl',   395, 7000, 'jdsports-nl.json'),
  new DutchSeedSource('bever.nl',      'Bever',      'https://www.bever.nl',      495, 5000, 'bever-nl.json'),
  new DutchSeedSource('intersport.nl', 'Intersport', 'https://www.intersport.nl', 495, 5000, 'intersport-nl.json'),
  new DutchSeedSource('bol.com',       'bol.com',    'https://www.bol.com',         0,    0, 'bol-com.json'),
];
