import { createGunzip } from 'node:zlib';
import { createReadStream, createWriteStream } from 'node:fs';
import { open, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import type { RetailerSource, FetchResult, RawOffer } from './types';

/**
 * GSM Net (gsm-net.nl) — Awin affiliate PRODUCT FEED adapter.
 *
 * The first affiliate-network retailer on Scoopt, alongside the eBay API
 * sources. Everything downstream of RetailerSource is retailer-agnostic (see
 * ./types.ts), so this is the ONE new file the design asks for: it turns
 * GSM Net's Awin product feed into RawOffers and the machine does the rest.
 *
 * MEMORY: the feed is large (~39k rows). An earlier version downloaded the whole
 * gzipped file, unzipped all of it, turned it into one string, and parsed that
 * into a full in-memory table, plus kept a full copy to archive. That held
 * several copies of a big feed at once and OOM-killed the ~2GB Railway cron
 * container (eBay never hits this because it pages a small API). This version
 * STREAMS instead: it downloads to a temp file, then decompresses and parses it
 * row by row, holding only one row plus the growing offers list. Peak memory is
 * bounded and independent of feed size.
 *
 * SETUP (see README-AWIN.md): Awin > Toolbox > Create-a-Feed, advertiser GSM Net,
 * language Dutch, CSV / comma / gzip, columns including aw_deep_link, product_name,
 * aw_product_id, ean, product_GTIN, brand_name, search_price, currency, in_stock,
 * aw_image_url, merchant_category, description. Put the feed URL in .env as
 * GSMNET_FEED_URL. Run: npm run ingest -- gsm-net
 */

const DEFAULT_CATEGORY = (process.env.GSMNET_CATEGORY ?? 'tech').toLowerCase();

/** Column aliases, in priority order. First non-empty cell wins. All lower-case. */
const COLUMNS = {
  sku: ['aw_product_id', 'merchant_product_id', 'product_id', 'mpn', 'ean'],
  ean: ['ean', 'gtin', 'product_gtin', 'ean_code', 'product_ean', 'gtin_ean'],
  brand: ['brand_name', 'brand', 'manufacturer', 'brand_id'],
  title: ['product_name', 'product_title', 'title', 'product_short_description'],
  price: ['search_price', 'store_price', 'price', 'product_price', 'display_price', 'price_incl_vat'],
  shipping: ['delivery_cost', 'shipping_cost', 'delivery_charges'],
  currency: ['currency', 'curr', 'price_currency'],
  inStock: ['in_stock', 'stock_status', 'is_in_stock', 'availability', 'stock'],
  url: ['aw_deep_link', 'deep_link', 'merchant_deep_link', 'aw_product_url', 'product_url'],
  image: ['aw_image_url', 'merchant_image_url', 'large_image', 'image_url', 'aw_thumb_url', 'image'],
  description: ['description', 'product_short_description', 'specifications', 'product_description'],
  category: ['merchant_category', 'category_name', 'merchant_product_category', 'product_type', 'category'],
} as const;

const UA =
  process.env.HTTP_USER_AGENT ??
  'Scoopt/0.1 (price comparison; +https://scoopt.nl; contact@scoopt.nl)';

export class GsmNetSource implements RetailerSource {
  readonly slug = 'gsm-net';
  readonly name = 'GSM Net';
  readonly homepageUrl = 'https://www.gsm-net.nl';
  readonly sourceKind = 'affiliate_feed' as const;
  readonly affiliateNetwork = 'awin';

  constructor(
    private readonly feedUrl: string = requireFeedUrl(),
    /** The feed is generated by us as comma-separated; override if that changes. */
    private readonly delimiter: string = process.env.GSMNET_FEED_DELIMITER ?? ','
  ) {}

  async fetch(): Promise<FetchResult> {
    const tmp = join(tmpdir(), `gsmnet-feed-${process.pid}-${Date.now()}.bin`);

    const res = await fetch(this.feedUrl, { headers: { 'user-agent': UA, accept: '*/*' } });
    if (!res.ok || !res.body) {
      throw new Error(`HTTP ${res.status} downloading GSM Net feed from ${hostOf(this.feedUrl)}`);
    }
    // Stream the download straight to disk so the whole feed is never in memory.
    await pipeline(Readable.fromWeb(res.body as unknown as Parameters<typeof Readable.fromWeb>[0]),
      createWriteStream(tmp));

    try {
      const gzip = await isGzipFile(tmp);
      const fileStream = createReadStream(tmp);
      const stream = gzip ? fileStream.pipe(createGunzip()) : fileStream;
      stream.setEncoding('utf8');

      const offers: RawOffer[] = [];
      let index: ColIndex | null = null;
      let header: string[] = [];
      let dataRows = 0;
      let skipped = 0;
      let sample = '';

      const parser = makeRowParser(this.delimiter, (row) => {
        if (!index) {
          header = row.map(normaliseHeader);
          index = buildIndex(header);
          // aw_deep_link is the commission-bearing link. Without a URL column the
          // feed is useless for Scoopt, so fail loudly rather than import dead rows.
          if (col(index, COLUMNS.url) < 0) {
            throw new Error(
              `GSM Net feed has no deep-link column. Add "aw_deep_link" in Create-a-Feed ` +
              `(header seen: ${header.join(', ')}).`
            );
          }
          return;
        }
        dataRows++;
        const offer = toRawOffer(row, index);
        if (offer) offers.push(offer);
        else skipped++;
      });

      for await (const chunk of stream as AsyncIterable<string>) {
        if (sample.length < 16384) sample += chunk;
        parser.push(chunk);
      }
      parser.end();

      console.log(
        `  [${this.slug}] ${offers.length} offers parsed, ${skipped} rows skipped (no url/price), ` +
        `${dataRows} data rows`
      );

      // Archive a COMPACT record, not the whole feed, so nothing large is held or
      // written. The parsed offers are the useful artefact; this keeps enough
      // (header, delimiter, a head sample) to debug a parsing problem.
      const rawPayload = JSON.stringify({
        source: this.slug,
        fetchedAt: new Date().toISOString(),
        host: hostOf(this.feedUrl),
        delimiter: this.delimiter,
        gzip,
        header,
        dataRows,
        offers: offers.length,
        skipped,
        note: 'streamed; full feed not archived inline to bound memory',
        sample: sample.slice(0, 16384),
      }, null, 2);

      return { offers, rawPayload };
    } finally {
      await rm(tmp, { force: true }).catch(() => {});
    }
  }
}

// ---------------------------------------------------------------------------
// setup / helpers
// ---------------------------------------------------------------------------

function requireFeedUrl(): string {
  const url = process.env.GSMNET_FEED_URL;
  if (!url) {
    throw new Error(
      'GSMNET_FEED_URL is not set.\n' +
      '  → Awin → Toolbox → Create-a-Feed → GSM Net → copy the feed URL into .env'
    );
  }
  return url;
}

function hostOf(url: string): string {
  try { return new URL(url).host; } catch { return url; }
}

/** gzip magic bytes 0x1f 0x8b — Awin serves gzip whether or not the URL says .gz. */
async function isGzipFile(path: string): Promise<boolean> {
  const fh = await open(path, 'r');
  try {
    const buf = Buffer.alloc(2);
    const { bytesRead } = await fh.read(buf, 0, 2, 0);
    return bytesRead === 2 && buf[0] === 0x1f && buf[1] === 0x8b;
  } finally {
    await fh.close();
  }
}

// ---------------------------------------------------------------------------
// Streaming CSV parser (RFC 4180: quotes, escaped "" quotes, embedded
// commas/newlines). Fed arbitrary chunks; emits one complete row at a time.
// State is kept across chunks, including a pending-quote flag so an escaped
// quote split across a chunk boundary is handled correctly.
// ---------------------------------------------------------------------------

interface RowParser {
  push(chunk: string): void;
  end(): void;
}

export function makeRowParser(delimiter: string, onRow: (row: string[]) => void): RowParser {
  let inQuotes = false;
  let quotePending = false; // saw a '"' while inQuotes; the next char decides
  let field = '';
  let row: string[] = [];

  const endField = () => { row.push(field); field = ''; };
  const endRow = () => {
    endField();
    // Skip fully blank lines rather than emitting an empty row.
    if (row.length > 1 || row[0] !== '') onRow(row);
    row = [];
  };

  return {
    push(chunk: string) {
      for (let i = 0; i < chunk.length; i++) {
        const c = chunk[i];
        if (quotePending) {
          quotePending = false;
          if (c === '"') { field += '"'; continue; } // "" inside quotes -> literal "
          inQuotes = false; // it was the closing quote; handle c as outside-quotes
        }
        if (inQuotes) {
          if (c === '"') quotePending = true;
          else field += c;
          continue;
        }
        if (c === '"') { inQuotes = true; continue; }
        if (c === delimiter) { endField(); continue; }
        if (c === '\r') continue;
        if (c === '\n') { endRow(); continue; }
        field += c;
      }
    },
    end() {
      if (quotePending) { quotePending = false; inQuotes = false; }
      if (field.length > 0 || row.length > 0) endRow();
    },
  };
}

// ---------------------------------------------------------------------------
// header mapping + row -> RawOffer
// ---------------------------------------------------------------------------

function normaliseHeader(h: string): string {
  return h.trim().toLowerCase().replace(/^﻿/, '').replace(/^"|"$/g, '');
}

type ColIndex = Map<string, number>;

function buildIndex(header: string[]): ColIndex {
  const m: ColIndex = new Map();
  header.forEach((h, i) => { if (!m.has(h)) m.set(h, i); });
  return m;
}

/** Index of the first alias present in the header, or -1. */
function col(index: ColIndex, aliases: readonly string[]): number {
  for (const a of aliases) {
    const i = index.get(a);
    if (i !== undefined) return i;
  }
  return -1;
}

/** First non-empty cell across the alias list. */
function pick(row: string[], index: ColIndex, aliases: readonly string[]): string {
  for (const a of aliases) {
    const i = index.get(a);
    if (i !== undefined) {
      const v = (row[i] ?? '').trim();
      if (v) return v;
    }
  }
  return '';
}

function toRawOffer(row: string[], index: ColIndex): RawOffer | null {
  const url = pick(row, index, COLUMNS.url);
  if (!url.startsWith('http')) return null; // no tracked link -> nothing to earn/show

  const priceCents = parsePriceToCents(pick(row, index, COLUMNS.price));
  if (priceCents === null) return null;

  const title = pick(row, index, COLUMNS.title);
  if (!title) return null;

  const eanRaw = pick(row, index, COLUMNS.ean);
  const shippingStr = pick(row, index, COLUMNS.shipping);
  const shippingCents = shippingStr ? (parsePriceToCents(shippingStr) ?? 0) : 0;
  const currency = (pick(row, index, COLUMNS.currency) || 'EUR').toUpperCase();
  const categoryLabel = pick(row, index, COLUMNS.category);

  return {
    retailerSku: pick(row, index, COLUMNS.sku) || eanRaw || url,
    ean: eanRaw || null,
    brand: pick(row, index, COLUMNS.brand) || 'Onbekend',
    title,
    category: DEFAULT_CATEGORY,
    priceCents,
    shippingCents,
    currency,
    inStock: parseInStock(pick(row, index, COLUMNS.inStock)),
    productUrl: url,
    imageUrl: pick(row, index, COLUMNS.image) || null,
    description: pick(row, index, COLUMNS.description) || null,
    sourceCategoryKey: categoryLabel || null,
    sourceCategoryLabel: categoryLabel || null,
  };
}

/**
 * Parse a feed price string to integer cents, tolerating the formats a product
 * feed can emit: "1299.00", "1.299,00", "1299,00", "€ 1299", "1299".
 */
export function parsePriceToCents(input: string): number | null {
  if (!input) return null;
  let s = input.replace(/[^\d.,-]/g, '').trim();
  if (!s) return null;

  const hasDot = s.includes('.');
  const hasComma = s.includes(',');
  if (hasDot && hasComma) {
    if (s.lastIndexOf(',') > s.lastIndexOf('.')) s = s.replace(/\./g, '').replace(',', '.');
    else s = s.replace(/,/g, '');
  } else if (hasComma) {
    s = /,\d{1,2}$/.test(s) ? s.replace(',', '.') : s.replace(/,/g, '');
  }
  const value = Number(s);
  if (!Number.isFinite(value) || value <= 0) return null;
  return Math.round(value * 100);
}

const IN_STOCK_TRUE = new Set(['1', 'y', 'yes', 'true', 't', 'in stock', 'instock', 'in_stock', 'op voorraad', 'available', 'leverbaar']);
const IN_STOCK_FALSE = new Set(['0', 'n', 'no', 'false', 'f', 'out of stock', 'outofstock', 'uit voorraad', 'unavailable', 'niet leverbaar', 'nietopvoorraad']);

/** Feeds spell stock a dozen ways. Unknown -> assume buyable (default true). */
export function parseInStock(value: string): boolean {
  const v = value.trim().toLowerCase();
  if (!v) return true;
  if (IN_STOCK_TRUE.has(v)) return true;
  if (IN_STOCK_FALSE.has(v)) return false;
  const n = Number(v);
  if (Number.isFinite(n)) return n > 0;
  return true;
}
